package vista;

/**
 *
 * @author HP
 */
public class DlgMainCliente extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DlgMainCliente.class.getName());

    /**
     * Creates new form DlgNewCliente
     */
    public DlgMainCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    private java.util.ArrayList<logica.Cliente> listaCli;
    private javax.swing.table.DefaultTableModel model;

    public DlgMainCliente(java.awt.Frame parent, boolean modal,
            java.util.ArrayList<logica.Cliente> listaCli) {
        super(parent, modal);
        initComponents();
        this.listaCli = listaCli;
    }

    public java.util.ArrayList<logica.Cliente> getListaCli() {
        return listaCli;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblBuscar = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnInsertar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        bntEliminar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        lblCantClientes = new javax.swing.JLabel();
        txtCantClientes = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        lblBuscar.setText("Buscar");

        txtBuscar.addActionListener(this::txtBuscarActionPerformed);

        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(this::btnInsertarActionPerformed);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(this::btnEditarActionPerformed);

        bntEliminar.setText("Eliminar");
        bntEliminar.addActionListener(this::bntEliminarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnInsertar)
                .addGap(46, 46, 46)
                .addComponent(btnEditar)
                .addGap(41, 41, 41)
                .addComponent(bntEliminar)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscar)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInsertar)
                    .addComponent(btnEditar)
                    .addComponent(bntEliminar))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Cédula", "Nombre", "Fecha Nac.", "Género", "Teléfono", "Dirección"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblClientes);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblCantClientes.setText("Cant. de clientes: ");

        txtCantClientes.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblCantClientes)
                .addGap(18, 18, 18)
                .addComponent(txtCantClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        String titulo[] = {"Cédula", "Nombre", "Fecha Nac.", "Género",
            "Teléfono", "Dirección"};

        logica.Cliente cli;
        model = new javax.swing.table.DefaultTableModel(null, titulo) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        for (int i = 0; i < listaCli.size(); i++) {
            cli = listaCli.get(i);

            if (String.valueOf(cli.getCedula()).toLowerCase().contains(txtBuscar.getText().toLowerCase())
                    || cli.getNombre().toLowerCase().contains(txtBuscar.getText().toLowerCase())) {
                Object row[] = {cli.getCedula(), cli.getNombre(), cli.getFechaNac(),
                    cli.getGenero(), cli.getTelefono(), cli.getDireccion()};
                model.addRow(row);
            }
        }

        tblClientes.setModel(model);
        txtCantClientes.setText(String.valueOf(tblClientes.getRowCount()));
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void bntEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntEliminarActionPerformed
        if (tblClientes.getSelectedRowCount() == 1) {
            int resp = javax.swing.JOptionPane.showConfirmDialog(this,
                    "¿Desea borrar el cliente seleccionado?");
            if (resp == 0) {
                int index = tblClientes.getSelectedRow();

                listaCli.remove(index);
                javax.swing.JOptionPane.showMessageDialog(this, "Cliente eliminado");
                muestraTabla();
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar un cliente");
        }
    }//GEN-LAST:event_bntEliminarActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        javax.swing.JFrame padre = (javax.swing.JFrame) this.getOwner();

        vista.DlgNewCliente winNew = new vista.DlgNewCliente(padre, true, listaCli, 1);
        winNew.setTitle("Agregar Cliente");
        winNew.setVisible(true);
        this.listaCli = winNew.getListaCli();
        muestraTabla();
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        muestraTabla();
    }//GEN-LAST:event_formWindowActivated

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (tblClientes.getSelectedRowCount() == 1) {
            int index = tblClientes.getSelectedRow();
            logica.Cliente cli = new logica.Cliente();

            cli.setCedula(Integer.parseInt(tblClientes.getValueAt(index, 0).toString()));
            cli.setNombre(tblClientes.getValueAt(index, 1).toString());
            java.time.LocalDate fecha = java.time.LocalDate.parse(
                    tblClientes.getValueAt(index, 2).toString());
            cli.setFechaNac(fecha);
            cli.setGenero(tblClientes.getValueAt(index, 3).toString());
            cli.setTelefono(Integer.parseInt(tblClientes.getValueAt(index, 4).toString()));
            cli.setDireccion(tblClientes.getValueAt(index, 5).toString());

            javax.swing.JFrame padre = (javax.swing.JFrame) this.getOwner();
            vista.DlgNewCliente winEdit = new vista.DlgNewCliente(padre, true, listaCli, 2, cli, index);
            winEdit.setLocationRelativeTo(null);
            winEdit.setTitle("Editar Cliente");
            winEdit.setVisible(true);
            this.listaCli = winEdit.getListaCli();
            muestraTabla();

        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Debe seleccionar un único registro");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void muestraTabla() {
        String titulo[] = {"Cédula", "Nombre", "Fecha Nac.", "Género", "Teléfono", "Dirección"};
        model = new javax.swing.table.DefaultTableModel(null, titulo) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        for (int i = 0; i < listaCli.size(); i++) {
            logica.Cliente cli = listaCli.get(i);
            Object row[] = {cli.getCedula(), cli.getNombre(), cli.getFechaNac(),
                cli.getGenero(), cli.getTelefono(), cli.getDireccion()};
            model.addRow(row);
        }

        tblClientes.setModel(model);
        txtCantClientes.setText(String.valueOf(tblClientes.getRowCount()));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DlgMainCliente dialog = new DlgMainCliente(new javax.swing.JFrame(), true, new java.util.ArrayList<>());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntEliminar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblCantClientes;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCantClientes;
    // End of variables declaration//GEN-END:variables
}
